on:  
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Generate MSE with VerveineJ

permissions:
  contents: write

# define relative path of where VerveineJ should start its scan
env:
  SOURCE_ROOT: src

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: main
              
      - name: Check out VerveineJ
        uses: actions/checkout@v3
        with:
          repository: moosetechnology/VerveineJ
          path: verveinej
              
      # add software dependencies here

      - name: Install java (for verveinej)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      # Run VerveineJ to generate an MSE of the java code
      - name: Generate the MSE
        run: $GITHUB_WORKSPACE/verveinej/verveinej.sh -o $GITHUB_WORKSPACE/main/$SOURCE_ROOT/FamixJavaModel.mse $GITHUB_WORKSPACE/main/$SOURCE_ROOT
        
      # Debug output
      - name: Echo the paths, verify MSE is there
        run: echo $GITHUB_WORKSPACE/main/$SOURCE_ROOT && echo ${{ github.workspace }}/main/${{ env.SOURCE_ROOT}} && ls $GITHUB_WORKSPACE/main/$SOURCE_ROOT 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/main
